# Generated by Django 4.2.16 on 2024-11-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mrp', models.FloatField()),
                ('mfg_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('quantity_in_stock', models.IntegerField()),
            ],
        ),
    ]
